"""add ai insights to audit_reports

Revision ID: b37af424189f
Revises: e645e31f04de
Create Date: 2026-01-14 13:59:52.466646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b37af424189f'
down_revision: Union[str, Sequence[str], None] = 'e645e31f04de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_reports', sa.Column('ai_summary', sa.String(), nullable=True))
    op.add_column('audit_reports', sa.Column('ai_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_reports', 'ai_recommendations')
    op.drop_column('audit_reports', 'ai_summary')
    # ### end Alembic commands ###
